apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: mlops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: pranavsrinivas2999/insurance-fastapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DAGSHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dagshub-secret
                  key: username
            - name: DAGSHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dagshub-secret
                  key: token
          #volumeMounts:
          #  - name: mlops-volume
          #    mountPath: /data

      #volumes:
      #  - name: mlops-volume
      #    persistentVolumeClaim:
      #      claimName: mlops-pvc