apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: mlops-system
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30081
