name: CD to DigitalOcean Kubernetes

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-1.148.0-linux-amd64.tar.gz -o doctl.tar.gz
          tar -xzf doctl.tar.gz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
          doctl kubernetes cluster kubeconfig save bc18a38d-71cc-4035-b49d-93f038407a45
          
      - name: Delete existing PVC (optional, only if safe)
        run: |
        kubectl delete pvc mlops-pvc -n mlops-system --ignore-not-found

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/volumes.yaml
          kubectl apply -f k8s/fastapi-deployment.yaml
          kubectl apply -f k8s/fastapi-service.yaml
          kubectl apply -f k8s/streamlit-deployment.yaml
          kubectl apply -f k8s/streamlit-service.yaml
      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/fastapi-deployment -n mlops-system
          kubectl rollout status deployment/streamlit-deployment -n mlops-system